language: go

dist: bionic

before_install:
  - openssl aes-256-cbc -K $encrypted_2edfaca96b9a_key -iv $encrypted_2edfaca96b9a_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

install:
  - gpg --batch --passphrase $GPG_PASSPHRASE --pinentry-mode loopback --import gpgsecret.asc
  - echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key B5C7C6EAA5B9B41A trust;
  - git reset --hard

env:
  - GO111MODULE=on

before_script:

script: 
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go run build.go

before_deploy:
  - go get github.com/itchio/gothub@master
  - git reset --hard

deploy:
  provider: script
  script: go run release.go
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - /^dependabot\/.*$/
